import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { SCOPE, stripComments, transform, verifyScopedOutput } from "./scopePreflightTransform";

/**
 * Generates a SCOPED copy of Tailwind's preflight for the prebuilt
 * stylesheet (`@vaneui/ui/css`). Importing a component library must not
 * globally reset the consumer's page — the unscoped preflight zeroed
 * h1–h6 margins, stripped button/input appearance, and reset lists
 * site-wide for non-Tailwind consumers with no opt-out.
 *
 * Every selector is suffixed with `:where([data-vane-type], [data-vane-type] *)`
 * (zero specificity added), so the normalizations VaneUI's components rely
 * on (border reset for border utilities, margin/padding zeroing, UA
 * appearance stripping) apply to VaneUI subtrees — including consumer
 * content placed inside VaneUI containers — and nowhere else. Rules that
 * can never match inside the scope (html, :host) drop out naturally.
 *
 * The string transforms live in scripts/scopePreflightTransform.ts (pure,
 * unit-tested in src/components/tests/scopePreflightTransform.test.ts);
 * this file is only the file-I/O runner around them.
 */

const require = createRequire(import.meta.url);
const preflightPath = require.resolve("tailwindcss/preflight.css");

const source = fs.readFileSync(preflightPath, "utf8");
const stripped = stripComments(source);
const scoped = transform(stripped);

// Integrity guard: the preflight dependency floats, and one invalid selector
// in a list silently drops the whole rule in the browser. If a future
// preflight shape would be mangled by the transform (unbalanced parens, scope
// suffix landing inside parens, dropped selectors), fail the build loudly
// here instead of ever writing corrupt CSS.
verifyScopedOutput(stripped, scoped);

const header = `/* AUTO-GENERATED by scripts/scopePreflight.ts — do not edit, not committed.
   Tailwind's preflight with every selector scoped to VaneUI subtrees via
   ${SCOPE} so the prebuilt stylesheet never globally resets a consumer page. */
`;

const outPath = path.resolve("src/components/css/generated-scoped-preflight.css");
fs.writeFileSync(outPath, header + scoped);
console.log(`Scoped preflight written to ${path.relative(process.cwd(), outPath)} (${scoped.length} bytes)`);
