import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

/**
 * Generates a SCOPED copy of Tailwind's preflight for the prebuilt
 * stylesheet (`@vaneui/ui/css`). Importing a component library must not
 * globally reset the consumer's page — the unscoped preflight zeroed
 * h1–h6 margins, stripped button/input appearance, and reset lists
 * site-wide for non-Tailwind consumers with no opt-out.
 *
 * Every selector is suffixed with `:where([data-vane-type], [data-vane-type] *)`
 * (zero specificity added), so the normalizations VaneUI's components rely
 * on (border reset for border utilities, margin/padding zeroing, UA
 * appearance stripping) apply to VaneUI subtrees — including consumer
 * content placed inside VaneUI containers — and nowhere else. Rules that
 * can never match inside the scope (html, :host) drop out naturally.
 */

const require = createRequire(import.meta.url);
const preflightPath = require.resolve("tailwindcss/preflight.css");

const SCOPE = ":where([data-vane-type], [data-vane-type] *)";

const scopeSelectorList = (selectorList: string): string =>
  selectorList
    .split(",")
    .map((sel) => {
      const s = sel.trim().replace(/\s+/g, " ");
      if (!s) return s;
      // pseudo-elements must stay rightmost: `input::placeholder` becomes
      // `input:where(SCOPE)::placeholder`; bare `::before` becomes
      // `:where(SCOPE)::before`
      const pseudoIdx = s.indexOf("::");
      if (pseudoIdx !== -1) {
        return `${s.slice(0, pseudoIdx)}${SCOPE}${s.slice(pseudoIdx)}`;
      }
      return `${s}${SCOPE}`;
    })
    .join(",\n");

const stripComments = (css: string): string => css.replace(/\/\*[\s\S]*?\*\//g, "");

// recursive prelude{body} walker: at-rule preludes pass through with their
// bodies transformed; selector lists get scoped; declaration bodies copy
// verbatim
function transform(css: string): string {
  let out = "";
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf("{", i);
    if (open === -1) {
      out += css.slice(i);
      break;
    }
    const prelude = css.slice(i, open).trim();
    let depth = 1;
    let j = open + 1;
    while (j < css.length && depth > 0) {
      if (css[j] === "{") depth++;
      else if (css[j] === "}") depth--;
      j++;
    }
    const body = css.slice(open + 1, j - 1);
    if (prelude.startsWith("@")) {
      out += `${prelude.replace(/\s+/g, " ")} {\n${transform(body)}}\n`;
    } else {
      out += `${scopeSelectorList(prelude)} {${body}}\n`;
    }
    i = j;
  }
  return out;
}

const source = fs.readFileSync(preflightPath, "utf8");
const scoped = transform(stripComments(source));

const header = `/* AUTO-GENERATED by scripts/scopePreflight.ts — do not edit, not committed.
   Tailwind's preflight with every selector scoped to VaneUI subtrees via
   ${SCOPE} so the prebuilt stylesheet never globally resets a consumer page. */
`;

const outPath = path.resolve("src/components/css/generated-scoped-preflight.css");
fs.writeFileSync(outPath, header + scoped);
console.log(`Scoped preflight written to ${path.relative(process.cwd(), outPath)} (${scoped.length} bytes)`);
